scripts:
  admin-webapp-configure-rails-db:
    start_when:
      datalayer-configure-rails-db passed:
        script_key: datalayer-configure-rails-db
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      ln -s $DATALAYER_DIR/config/database.yml  $ADMIN_WEBAPP_DIR/config/database.yml
  test:
    start_when:
      admin-webapp-configure-rails-db has passed:
        script_key: admin-webapp-configure-rails-db
