jobs:

  rspec-tests:
    name: "RSpec Tests"
    run_when: &DEFAULT_TRIGGERS
      the branch does not match no-ci or _wip_:
        type: branch
        include_match: &default_branch_match    ^.+$
        exclude_match: &default_branch_exclude  ^(.*no-ci.*)|([a-z]*_wip_.*)$
    context:
      include: cider-ci/rspec-tests.yml

  code-checks:
    name: "Code Checks"
    description: |
      Run static checks and metrics: complexity, duplication, and format.
    priority: 3
    run_when: *DEFAULT_TRIGGERS
    context:
      include: cider-ci/code-checks.yml

  delivery-tests:
    name: "Delivery Tests"
    run_when: *DEFAULT_TRIGGERS
    context:
      include: cider-ci/delivery-tests.yml

  meta-checks:
    name: Meta
    description: |
      Tasks that rely on external (out-of-repository) state.
      Their state is not as fixed as in the other Jobs, so it might change over time.
    priority: 3 # "I don't always run this, but when I do, it should be fast"
    run_when: *DEFAULT_TRIGGERS
    context:
      include:
        - path: cider-ci/contexts/meta-checks.yml
          submodule: [datalayer]
      task_defaults:
        environment_variables:
          GIT_LINEAR_HISTORY_CHECK_START_SHA: 1db79da0a0bf228d36475e8ae7212f9df39d049b


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  all-tests:
    name: "All tests"
    description: |
      This job depends on all unit jobs that need to pass.
      It is depended upon by the super-project!
    priority: 999 # "empty" job = high priority
    context:
      task: "echo '✔︎ All dependencies have passed' ; exit 0"
    run_when: *DEFAULT_TRIGGERS
    depends_on:
      rspec-tests:    {job_key: rspec-tests,    type: job, states: [passed]}
      delivery-tests: {job_key: delivery-tests, type: job, states: [passed]}
      all-tests of the datalayer: {job_key: all-tests, type: job, submodule: [datalayer], states: [passed]}

  good-to-merge:
    name: "Good To Merge"
    description: |
      This job depends on all jobs that need to pass for "Delivery".
      It is depended upon by GitHub's branch protection (for `master`)!
    priority: 999 # "empty" job = high priority
    context:
      task: "echo '✔︎ All dependencies have passed' ; exit 0"
    run_when: *DEFAULT_TRIGGERS
    depends_on:
      all-tests:      {job_key: all-tests,    type: job, states: [passed]}
      meta-checks:    {job_key: meta-checks,    type: job, states: [passed]}
      good to merge of the datalayer: {job_key: good-to-merge, type: job, submodule: [datalayer], states: [passed]}

