madek_admin_webapp_dir: /madek/server/admin-webapp
madek_admin_webapp_clean_slate: false
madek_admin_webapp_user: "{{madek_user}}"
madek_admin_webapp_max_threads_per_worker: 2
madek_admin_webapp_workers: "{{ ansible_facts['processor_vcpus'] }}"
madek_admin_webapp_puma_worker_killer_enabled: yes
madek_admin_webapp_puma_worker_killer_ram: '{{ (ansible_facts["memtotal_mb"] / 8) | int }}'
