jobs:

  code-checks:

    name: Code-Checks

    description: |
      Run static checks and metrics: complexity, duplication, and format.

    priority: 3

    run-on:
    - type: branch
      include-match: ^.+$
      exclude-match: ^.*no-ci.*$


    context:

      task-defaults:
        git-options:
          submodules:
            clone: true
            timeout: 60
        eager-trials: 1
        max-auto-trials: 2
        traits:
          linux: true
          bash: true

      subcontexts:
        ruby:
          task-defaults:
            traits:
              rbenv: true
              ruby: true
            environment-variables:
              RAILS_ENV: test
              LANG: "en_US.UTF-8"

          tasks:

            code_complexity:
              name: 'Ruby: Code complexity with flog'
              scripts:
                test:
                  body: |
                    #!/usr/bin/env bash
                    set -eux
                    export PATH=$(pwd)/vendor/jruby/bin/:$(ruby -e "puts ENV['PATH'].split(':').reject{|s| s.match(/\.rbenv/)}.join(':')")
                    jruby --dev -S bundle exec cider-ci_flog app/


            code_similarity:
              name: 'Ruby: Code similarity with flay'
              scripts:
                test:
                  body: |
                    #!/usr/bin/env bash
                    set -eux
                    export PATH=$(pwd)/vendor/jruby/bin/:$(ruby -e "puts ENV['PATH'].split(':').reject{|s| s.match(/\.rbenv/)}.join(':')")
                    jruby --dev -S bundle exec cider-ci_flay -m 36 app/


        git:
          description: 'Git sanity checks (fixed state)'
          task-defaults:
            max-auto-trials: 1
            traits:
              git: true
          tasks:
            linear_history:
              name: 'Git: Linear History'
              scripts:
                test:
                  body: cider-ci/bin/check-if-linear-history
